### ISSUE TITLE
Install via browser did not work

### ISSUE THREAD

**Issue by Hamishsw** [koenvervloesem/M5Stack-Air-Quality-ESPHome#10]
I tried to install my chrome browser. Was able to connect via USB, erase and the install completed however when I saw and clicked the next button it went back to the start page and looking at logs there is problems. I am not an engineer so do not know how to proceed. 

ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    59][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!
[  3247][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  4347][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Temperature': Sending state 128.86732 °C with 2 decimals of accuracy
[  5378][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  6418][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Humidity': Sending state 118.00000 % with 2 decimals of accuracy
E (7439) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7439) task_wdt:  - loopTask (CPU 1)
E (7439) task_wdt: Tasks currently running:
E (7439) task_wdt: CPU 0: IDLE
E (7439) task_wdt: CPU 1: IDLE
E (7439) task_wdt: Aborting.

abort() was called at PC 0x400ff368 on core 0

Backtrace:0x40083e49:0x3ffbeaac |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 1 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    59][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!
[  3246][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  4346][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Temperature': Sending state 128.86732 °C with 2 decimals of accuracy
[  5377][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  6417][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Humidity': Sending state 118.00000 % with 2 decimals of accuracy
E (7438) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7438) task_wdt:  - loopTask (CPU 1)
E (7438) task_wdt: Tasks currently running:
E (7438) task_wdt: CPU 0: IDLE
E (7438) task_wdt: CPU 1: IDLE
E (7438) task_wdt: Aborting.

abort() was called at PC 0x400ff368 on core 0

Backtrace:0x40083e49:0x3ffbeaac |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 2 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    59][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 8 restarts
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!
[  3398][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  4498][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Temperature': Sending state 128.86732 °C with 2 decimals of accuracy
[  5529][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  6569][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Humidity': Sending state 118.00000 % with 2 decimals of accuracy
E (7588) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7588) task_wdt:  - loopTask (CPU 1)
E (7588) task_wdt: Tasks currently running:
E (7588) task_wdt: CPU 0: IDLE
E (7588) task_wdt: CPU 1: IDLE
E (7588) task_wdt: Aborting.

abort() was called at PC 0x400ff368 on core 0

Backtrace:0x40083e49:0x3ffbeaac |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 3 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    59][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 7 restarts
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!
[  3408][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  4508][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Temperature': Sending state 128.86732 °C with 2 decimals of accuracy
[  5539][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  6579][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Humidity': Sending state 118.00000 % with 2 decimals of accuracy
E (7599) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7599) task_wdt:  - loopTask (CPU 1)
E (7599) task_wdt: Tasks currently running:
E (7599) task_wdt: CPU 0: IDLE
E (7599) task_wdt: CPU 1: IDLE
E (7599) task_wdt: Aborting.

abort() was called at PC 0x400ff368 on core 0

Backtrace:0x40083e49:0x3ffbeaac |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 4 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    59][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 6 restarts
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!
[  3254][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  4354][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Temperature': Sending state 128.86732 °C with 2 decimals of accuracy
[  5385][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  6425][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Humidity': Sending state 118.00000 % with 2 decimals of accuracy
E (7446) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7446) task_wdt:  - loopTask (CPU 1)
E (7446) task_wdt: Tasks currently running:
E (7446) task_wdt: CPU 0: IDLE
E (7446) task_wdt: CPU 1: IDLE
E (7446) task_wdt: Aborting.

abort() was called at PC 0x400ff368 on core 0

Backtrace:0x40083e49:0x3ffbeaac |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 5 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    59][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 5 restarts
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!
[  3247][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  4347][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Temperature': Sending state 128.86732 °C with 2 decimals of accuracy
[  5378][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  6418][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Humidity': Sending state 118.00000 % with 2 decimals of accuracy
E (7439) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7439) task_wdt:  - loopTask (CPU 1)
E (7439) task_wdt: Tasks currently running:
E (7439) task_wdt: CPU 0: IDLE
E (7439) task_wdt: CPU 1: IDLE
E (7439) task_wdt: Aborting.

abort() was called at PC 0x400ff368 on core 0

Backtrace:0x40083e49:0x3ffbeaac |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 6 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    59][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 4 restarts
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!
[  3255][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  4355][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Temperature': Sending state 128.86732 °C with 2 decimals of accuracy
[  5386][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  6426][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[D][sensor:127]: 'Humidity': Sending state 118.00000 % with 2 decimals of accuracy
E (7447) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7447) task_wdt:  - loopTask (CPU 1)
E (7447) task_wdt: Tasks currently running:
E (7447) task_wdt: CPU 0: IDLE
E (7447) task_wdt: CPU 1: IDLE
E (7447) task_wdt: Aborting.

abort() was called at PC 0x400ff368 on core 0

Backtrace:0x40083e49:0x3ffbeaac |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (217) psram: PSRAM ID read error: 0xffffffff
[I][logger:258]: Log initialized
[C][ota:469]: There have been 7 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[C][spi:023]: Setting up SPI bus...
[C][uart.arduino_esp32:077]: Setting up UART...
[    60][E][HardwareSerial.cpp:525] setRxBufferSize(): RX Buffer can't be resized when Serial is already running.

[D][ledc.output:051]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:056]: Resolution calculated as 16
[E][display:109]: Could not allocate buffer for display!
[D][binary_sensor:034]: 'M5_BtnB': Sending initial state OFF
[C][light:036]: Setting up light 'Display Backlight'...
[D][light:035]: 'Display Backlight' Setting:
[D][light:040]:   Color mode: 
[D][light:046]:   State: ON
[D][light:084]:   Transition length: 1.0s
[  1440][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[E][SHT20:021]: Sensor is not connected
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 08:B6:1F:87:43:C4
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'm5stack-air-quality-kit-8743c4'
[C][wifi:213]:   AP Password: '12345678'
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:386]: Starting scan...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: m5stack-air-quality-kit.local:3232
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 3 restarts
[C][api:025]: Setting up Home Assistant API server...
[D][wifi:386]: Starting scan...
[I][app:062]: setup() finished successfully!

**Comment by Hamishsw** [comment]
Update - I managed to get this project working by hooking the hardware up to my Pi running HA and then grabbing the YAML for the PM sensors and the code for display setup. I ended up leaving off the lines for temp/humidity and simply made the remaining display text bigger and more spaced out. 
so thanks for this project!
![IMG_2212](https://github.com/koenvervloesem/M5Stack-Air-Quality-ESPHome/assets/100760926/1975253f-efe0-4931-b2f6-c6d4ab4987b6)

**Comment by Hamishsw** [comment]
Fixed thanks.

**Comment by koenvervloesem** [comment]
I'm not sure what was going wrong, I see some I²C errors and weird temperature and humidity values in your logs, maybe some faulty hardware? But I'm glad you got the PM sensor working!

**Comment by jkeilson** [comment]
@Hamishsw I'm seeing the same issue, see #11 . Do you have the yaml you used available somewhere? I don't believe the issue is faulty hardware, because the default example firmware was working, and I was able to reflash with UIFlow, and that seems to be working.

**Comment by Hamishsw** [comment]
> @Hamishsw I'm seeing the same issue, see #11 . Do you have the yaml you used available somewhere? I don't believe the issue is faulty hardware, because the default example firmware was working, and I was able to reflash with UIFlow, and that seems to be working.

Yup sure will link you tomorrow.

**Comment by Hamishsw** [comment]
@jkeilson here is the yaml I use within ESPHome. Sensitive info removed. Hope it helps.

`esphome:
  name: m5stackcore
  friendly_name: M5StackCore

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stackcore Fallback Hotspot"
    password: ""

captive_portal:
uart:
  rx_pin: 16
  baud_rate: 9600

i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 200kHz

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

# Particulate matter sensor and temperature sensor
sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "PM1"
      id: sensor_pm1
      filters:
        - sliding_window_moving_average:
            window_size: 180
            send_every: 60
    pm_2_5:
      name: "PM2.5"
      id: sensor_pm25
      filters:
        - sliding_window_moving_average:
            window_size: 180
            send_every: 60
    pm_10_0:
      name: "PM10"
      id: sensor_pm10
      filters:
        - sliding_window_moving_average:
            window_size: 180
            send_every: 60

binary_sensor:
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    on_click:
      then:
        - light.toggle: back_light

font:
  - file: "gfonts://Roboto@medium"
    id: font_roboto_medium22
    size: 34
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/³µ'

color:
  - id: RED
    red: 100%
    green: 0%
    blue: 0%
  - id: BLUE
    red: 0%
    green: 0%
    blue: 100%
  - id: WHITE
    red: 100%
    green: 100%
    blue: 100%

# GPIO pin of the display backlight
output:
  - platform: ledc
    pin: 32
    id: gpio_32_backlight_pwm
    
light:
  - platform: monochromatic
    output: gpio_32_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
    
display:
  - platform: ili9xxx
    id: m5stack_display
    model: M5Stack
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    rotation: 0
    lambda: |-
      it.rectangle(0,  0, it.get_width(), it.get_height(), BLUE);
      it.rectangle(0, 45, it.get_width(), it.get_height(), BLUE);   // header bar
      it.print(it.get_width() / 2, 20, id(font_roboto_medium22), RED, TextAlign::CENTER, "Particulate matter");

      it.print(11,  60, id(font_roboto_medium22), WHITE, TextAlign::LEFT, "PM1");
      it.print(11,  110, id(font_roboto_medium22), WHITE, TextAlign::LEFT, "PM2.5");
      it.print(11,  160, id(font_roboto_medium22), WHITE, TextAlign::LEFT, "PM10");

      it.printf(it.get_width() - 11,  60, id(font_roboto_medium22), WHITE, TextAlign::RIGHT, "%.0f µg/m³", id(sensor_pm1).state);
      it.printf(it.get_width() - 11,  110, id(font_roboto_medium22), WHITE, TextAlign::RIGHT, "%.0f µg/m³", id(sensor_pm25).state);
      it.printf(it.get_width() - 11,  160, id(font_roboto_medium22), WHITE, TextAlign::RIGHT, "%.0f µg/m³", id(sensor_pm10).state);

`
