### ISSUE TITLE
Support for multiple SHT20 Sensors

### ISSUE THREAD

**Issue by lukasdietz** [koenvervloesem/M5Stack-Air-Quality-ESPHome#6]
I would like to see support for more than one SHT20 Sensor. 
Is this a possible thing to do?

**Comment by koenvervloesem** [comment]
According to the [SHT20 datasheet](https://sensirion.com/resource/datasheet/sht20), the sensors all have the same I²C address, so there would be no way to distinguish them. So no, unfortunately it isn't possible to support more than one SHT20 sensor.
