### ISSUE TITLE
Display no longer working with current ESPHOme version

### ISSUE THREAD

**Issue by Tokn59** [koenvervloesem/M5Stack-Air-Quality-ESPHome#9]
Hi,

I recompiled my code with the latest ESPHome version 2023.11.3

The display no longer works. It stays "black". Pressing buttons doesn't help either.

<img width="591" alt="image" src="https://github.com/koenvervloesem/M5Stack-Air-Quality-ESPHome/assets/9215231/4acdca42-ae4d-42ef-b060-ef80f56c4d3b">

This is the (test) code I used, Any suggestions on what's wrong (the device works fine, no HW issue) THANK YOU !!!

`esphome:
  name: m5stack-test
  friendly_name: m5stack test
  platform: ESP32
  board: m5stack-core-esp32

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "gpjuhv2JrMwqJv0bmLgs4gQg4Y4CVm9RT5aBenud9RY="

ota:
  password: "b63b7141d7c6b173ed066b98706242d0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stack-Test Fallback Hotspot"
    password: "VAPrYAGk5uXM"

captive_portal:

web_server:
  port: 80  

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

font:
  - file: "fonts/Roboto-Medium.ttf"
    id: font_roboto_medium22
    size: 22
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/³µ'  

color:
  - id: RED
    red: 100%
    green: 0%
    blue: 0%
  - id: BLUE
    red: 0%
    green: 0%
    blue: 100%
  - id: WHITE
    red: 100%
    green: 100%
    blue: 100%

display:
  - platform: ili9xxx
    id: m5stack_display
    model: M5Stack
    cs_pin: 14
    dc_pin: 27
#    led_pin: 32
    reset_pin: 33
    rotation: 0
    lambda: |-
      it.rectangle(0,  0, it.get_width(), it.get_height(), BLUE);
      it.rectangle(0, 22, it.get_width(), it.get_height(), BLUE);   // header bar
      it.print(it.get_width() / 2, 11, id(font_roboto_medium22), RED, TextAlign::CENTER, "Particulate matter");
 `

**Comment by Hamishsw** [comment]
@Tokn59 don’t know if it helps but take a look at the issue I opened and just closed with me getting this working. Only installed ESP Home yesterday so assume is latest version.

**Comment by Tokn59** [comment]
@Hamishsw Thank you. I got it working. seems one of my M5stack modules display was dead !
